<?php

/**
 * Trust Payments Magento 1
 *
 * This Magento extension enables to process payments with Trust Payments (https://www.trustpayments.com//).
 *
 * @package TrustPayments_Payment
 * @author customweb GmbH (http://www.customweb.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */

/* @var TrustPayments_Payment_Block_Adminhtml_Sales_Order_View $block */
$block = $this;

/* @var TrustPayments_Payment_Helper_Data $helper */
$helper = $block->helper('trustpayments_payment');
?>
<?php if ($block->hasPendingRefund()) : ?>
    <div id="messages">
        <ul class="messages">
            <li class="notice-msg">
                <ul>
                    <li>
                        <span>
                            <?php echo $block->escapeHtml($helper->__('This order has a pending refund request.')) ?>
                        </span>
                        <span class="f-right">
                            <a href="<?php echo $block->escapeHtml($block->getRefundUrl()) ?>">
                                <?php echo $block->escapeHtml($helper->__('Send Refund Request')) ?>
                            </a>
                        </span>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
<?php endif; ?>