<?php

/**
 * Trust Payments Magento 1
 *
 * This Magento extension enables to process payments with Trust Payments (https://www.trustpayments.com//).
 *
 * @package TrustPayments_Payment
 * @author customweb GmbH (http://www.customweb.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */

/* @var TrustPayments_Payment_Block_Payment_Form $block */
$block = $this;

/* @var TrustPayments_Payment_Model_Payment_Method_Abstract $method */
$method = $block->getMethod();

/* @var TrustPayments_Payment_Helper_Data $helper */
$helper = $block->helper('trustpayments_payment');

$code = $block->getMethodCode();
$tokens = $block->getTokens();
$selectedToken = $this->getInfoData('trustpayments_token');
?>

<ul id="payment_form_<?php echo $block->escapeHtml($code) ?>" style="display:none">
    <li>
        <?php echo $block->escapeHtml($helper->__('A charge flow will be used to process the payment.')) ?>
    </li>
    <?php if (!empty($tokens)) : ?>
        <li>
            <div>
                <?php echo $block->escapeHtml($helper->__('The customer can be charged by using an existing token. If left empty, no token is used.')) ?>
            </div>
            <div class="input-box">
                <label for="<?php echo $block->escapeHtml($method->getCode()) ?>_token">
                    <?php echo $block->escapeHtml($helper->__('Token:')) ?>
                </label>
                <select
                    id="<?php echo $block->escapeHtml($method->getCode()) ?>_token"
                    name="payment[trustpayments_token]">
                    <option value=""></option>
                    <?php foreach ($tokens as $token) : ?>
                        <option
                            value="<?php echo $block->escapeHtml($token->getId()) ?>"
                            <?php echo $selectedToken == $token->getId() ? 'selected="selected"' : '' ?>>
                            <?php echo $block->escapeHtml($token->getName()) ?>
                            (<?php echo $block->escapeHtml($helper->translate($token->getConnector()->getName())) ?>)
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </li>
    <?php endif; ?>
</ul>