<?php

/**
 * Trust Payments Magento 1
 *
 * This Magento extension enables to process payments with Trust Payments (https://www.trustpayments.com//).
 *
 * @package TrustPayments_Payment
 * @author customweb GmbH (http://www.customweb.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */

/* @var TrustPayments_Payment_Block_Payment_Info $block */
$block = $this;

/* @var TrustPayments_Payment_Model_Payment_Method_Abstract $method */
$method = $block->getMethod();

/* @var TrustPayments_Payment_Helper_Data $helper */
$helper = $block->helper('trustpayments_payment');

$transactionInfo = $block->getTransactionInfo();
$labelsByGroup = $block->getGroupedChargeAttemptLabels();
if ($transactionInfo && $transactionInfo->getImage()) {
    $imageUrl = $helper->getResourceUrl(
        $transactionInfo->getImage(), $transactionInfo->getLanguage(),
        $transactionInfo->getSpaceId(), $transactionInfo->getSpaceViewId()
    );
}
?>

<?php if ($block->isCreditmemo()) : ?>
    <?php $refundDownloadUrl = $block->getDownloadRefundUrl(); ?>
    <?php if ($refundDownloadUrl) : ?>
        <button
            title="<?php echo $block->escapeHtml($helper->__('Download Refund')) ?>"
            type="button"
            class="scalable"
            onclick="setLocation('<?php echo $block->escapeHtml($refundDownloadUrl) ?>')"
            style="float: right;">
            <span><span><span><?php echo $block->escapeHtml($helper->__('Download Refund')) ?></span></span></span>
        </button>
    <?php endif; ?>
<?php endif; ?>

<?php if ($block->isInvoice()) : ?>
    <?php $invoiceDownloadUrl = $block->getDownloadInvoiceUrl(); ?>
    <?php if ($invoiceDownloadUrl) : ?>
    <button
        title="<?php echo $block->escapeHtml($helper->__('Download Invoice')) ?>"
        type="button"
        class="scalable"
        onclick="setLocation('<?php echo $block->escapeHtml($invoiceDownloadUrl) ?>')"
        style="float: right;">
        <span><span><span><?php echo $block->escapeHtml($helper->__('Download Invoice')) ?></span></span></span>
    </button>
    <?php endif; ?>
<?php endif; ?>

<?php if ($block->isShipment()) : ?>
    <?php $packingSlipDownloadUrl = $block->getDownloadPackingSlipUrl(); ?>
    <?php if ($packingSlipDownloadUrl) : ?>
    <button
        title="<?php echo $block->escapeHtml($helper->__('Download Packing Slip')) ?>"
        type="button"
        class="scalable"
        onclick="setLocation('<?php echo $block->escapeHtml($packingSlipDownloadUrl) ?>')"
        style="float: right;">
        <span><span><span><?php echo $block->escapeHtml($helper->__('Download Packing Slip')) ?></span></span></span>
    </button>
    <?php endif; ?>
<?php endif; ?>

<?php if (false && ! $block->isCreditmemo() && ! $block->isInvoice() && ! $block->isShipment()) : ?>
    <?php $transactionUpdateUrl = $block->getUpdateTransactionUrl(); ?>
    <?php if ($transactionUpdateUrl) : ?>
        <button
            title="<?php echo $block->escapeHtml($helper->__('Update')) ?>"
            type="button"
            class="scalable"
            onclick="setLocation('<?php echo $block->escapeHtml($transactionUpdateUrl) ?>')"
            style="float: right;">
            <span><span><span><?php echo $block->escapeHtml($helper->__('Update')) ?></span></span></span>
        </button>
    <?php endif; ?>
<?php endif; ?>

<table class="form-list" style="margin-bottom: 20px;">
    <tbody>
        <tr>
            <td class="label"><label><?php echo $block->escapeHtml($helper->__('Payment Method')) ?></label></td>
            <td class="value">
                <strong>
                    <?php echo $block->escapeHtml($method->getPaymentMethodConfiguration()->getConfigurationName()) ?>
                </strong>
            </td>
        </tr>
        <?php if ($transactionInfo && $transactionInfo->getImage()) : ?>
            <tr>
                <td class="label"></td>
                <td class="value">
                    <img src="<?php echo $block->escapeHtml($imageUrl) ?>" width="50" /><br/>
                </td>
            </tr>
        <?php endif; ?>
        <?php if ($transactionInfo) : ?>
            <tr>
                <td class="label"><label><?php echo $block->escapeHtml($helper->__('Transaction State')) ?></label></td>
                <td class="value">
                    <strong><?php echo $block->escapeHtml($block->getTransactionState()) ?></strong>
                </td>
            </tr>
            <?php if ($transactionInfo->getFailureReason() != null) : ?>
                <tr>
                    <td class="label">
                        <label><?php echo $block->escapeHtml($helper->__('Failure Reason')) ?></label>
                    </td>
                    <td class="value">
                        <strong><?php echo $block->escapeHtml($transactionInfo->getFailureReason()) ?></strong>
                    </td>
                </tr>
            <?php endif; ?>
            <tr>
                <td class="label">
                    <label><?php echo $block->escapeHtml($helper->__('Authorization Amount')) ?></label>
                </td>
                <td class="value">
                    <strong><?php echo $block->getTransactionCurrency()->format($transactionInfo->getAuthorizationAmount()) ?></strong>
                </td>
            </tr>
            <tr>
                <td class="label"><label><?php echo $block->escapeHtml($helper->__('Transaction')) ?></label></td>
                <td class="value">
                    <strong>
                        <a href="<?php echo $block->escapeHtml($block->getTransactionUrl()) ?>" target="_blank">
                            <?php echo $block->escapeHtml($helper->__('View in Trust Payments')) ?>
                        </a>
                    </strong>
                </td>
            </tr>
            <tr>
                <td class="label"><label><?php echo $block->escapeHtml($helper->__('Customer')) ?></label></td>
                <td class="value">
                    <strong>
                        <a href="<?php echo $block->escapeHtml($block->getCustomerUrl()) ?>" target="_blank">
                            <?php echo $block->escapeHtml($helper->__('View in Trust Payments')) ?>
                        </a>
                    </strong>
                </td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>

<?php if (!empty($labelsByGroup)) : ?>
    <?php foreach ($labelsByGroup as $group) : ?>
        <?php $groupId = $group['group']->getId() ?>
        <div
            class="trustpayments-payment-label-container"
            id="trustpayments-payment-label-container-<?php echo $block->escapeHtml($groupId) ?>">
            <div class="trustpayments-payment-label-group">
                <?php echo $block->escapeHtml($helper->translate($group['group']->getName())) ?>
            </div>
            <table class="form-list" style="margin-bottom: 20px;">
                <tbody>
                    <?php foreach ($group['labels'] as $label) : ?>
                        <tr>
                            <td class="label">
                                <label><?php echo $block->escapeHtml(
                                    $helper->translate($label['descriptor']->getName())
                                ) ?></label>
                            </td>
                            <td class="value">
                                <strong><?php echo $block->escapeHtml($label['value']) ?></strong>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>

        <script type="text/javascript">
            new trustpaymentsPaymentLabelContainer(
                'trustpayments-payment-label-container-<?php echo $block->escapeHtml($groupId) ?>'
            );
        </script>
    <?php endforeach; ?>
<?php endif; ?>