<?php

/**
 * Trust Payments Magento 1
 *
 * This Magento extension enables to process payments with Trust Payments (https://www.trustpayments.com//).
 *
 * @package TrustPayments_Payment
 * @author customweb GmbH (http://www.customweb.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */

/* @var TrustPayments_Payment_Block_Payment_Cart $block */
$block = $this;

$deviceScriptUrl = $block->getDeviceJavascriptUrl();
?>

<?php if ($deviceScriptUrl) : ?>
    <script type="text/javascript" src="<?php echo $block->escapeHtml($deviceScriptUrl) ?>"></script>
<?php endif; ?>