<?php

/**
 * Trust Payments Magento 1
 *
 * This Magento extension enables to process payments with Trust Payments (https://www.trustpayments.com//).
 *
 * @package TrustPayments_Payment
 * @author wallee AG (http://www.wallee.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */

/* @var TrustPayments_Payment_Block_Payment_Form $block */
$block = $this;

/* @var TrustPayments_Payment_Model_Payment_Method_Abstract $method */
$method = $block->getMethod();

$code = $block->getMethodCode();
$imageUrl = $block->getImageUrl();
$configurationId = $method->getPaymentMethodConfigurationId();
?>

<ul class="form-list" id="payment_form_<?php echo $block->escapeHtml($code) ?>" style="display:none">
    <?php if ($method->getConfigData('show_description')
        || ($method->getConfigData('show_image') && $imageUrl != null)) : ?>
        <li>
            <table style="width: 100%;">
                <tr>
                    <td>
                        <?php if ($method->getConfigData('show_description')) : ?>
                            <?php echo $block->escapeHtml($method->getConfigData('description')) ?>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($method->getConfigData('show_image') && $imageUrl != null) : ?>
                            <img src="<?php echo $block->escapeHtml($imageUrl) ?>" width="50" style="float: right;" />
                        <?php endif; ?>
                    </td>
                </tr>
            </table>
        </li>
    <?php endif; ?>
    <li>
        <div id="trustpayments_payment_method_form_<?php echo $block->escapeHtml($configurationId) ?>"></div>
        <script type="text/javascript">
            MageTrustPayments.Checkout.registerMethod(
                    '<?php echo $block->escapeHtml($code) ?>',
                    <?php echo $block->escapeHtml($method->getPaymentMethodConfiguration()->getConfigurationId()) ?>,
                    'trustpayments_payment_method_form_<?php echo $block->escapeHtml($configurationId) ?>'
            );
        </script>
    </li>
    <li>
        <div id="trustpayments_payment_method_form_<?php echo $block->escapeHtml($configurationId) ?>_errors">
        </div>
    </li>
</ul>