<?php

/**
 * Trust Payments Magento 1
 *
 * This Magento extension enables to process payments with Trust Payments (https://www.trustpayments.com//).
 *
 * @package TrustPayments_Payment
 * @author customweb GmbH (http://www.customweb.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */

/* @var TrustPayments_Payment_Block_Payment_Info $block */
$block = $this;

/* @var TrustPayments_Payment_Model_Payment_Method_Abstract $method */
$method = $block->getMethod();

/* @var TrustPayments_Payment_Helper_Data $helper */
$helper = $block->helper('trustpayments_payment');

$imageUrl = $block->getImageUrl();
?>

<div><?php echo $block->escapeHtml($method->getTitle()) ?></div>
<?php if ($method->getConfigData('show_image') && $imageUrl != null) : ?>
<img src="<?php echo $block->escapeHtml($imageUrl) ?>" width="50"
    style="margin-top: 10px;" />
<?php endif; ?>

<?php if ($block->isCustomerDownloadInvoiceAllowed() || $block->isCustomerDownloadPackingSlipAllowed()) : ?>
<div style="margin-top: 20px;">
        <?php $invoiceDownloadUrl = $block->getDownloadInvoiceUrl(); ?>
        <?php if ($block->isCustomerDownloadInvoiceAllowed() && $invoiceDownloadUrl) : ?>
                <a
        href="<?php echo $block->escapeHtml($invoiceDownloadUrl) ?>">
                    <?php echo $block->escapeHtml($helper->__('Download Invoice')) ?>
                </a><br />
        <?php endif; ?>

        <?php $packingSlipDownloadUrl = $block->getDownloadPackingSlipUrl(); ?>
        <?php if ($block->isCustomerDownloadPackingSlipAllowed() && $packingSlipDownloadUrl) : ?>
                <a
        href="<?php echo $block->escapeHtml($packingSlipDownloadUrl) ?>">
                    <?php echo $block->escapeHtml($helper->__('Download Packing Slip')) ?>
                </a><br />
        <?php endif; ?>
    </div>
<?php endif; ?>